services:
  postgresql-fwd-master:
    image: postgres:12
    container_name: postgresql-fwd-master
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    volumes:
      - postgresql-fwd-master-volume:/var/lib/postgresql/data

  postgresql-fwd-shard1:
    image: postgres:12
    container_name: postgresql-fwd-shard1
    depends_on:
      - postgresql-fwd-master
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    volumes:
      - postgresql-fwd-shard1-volume:/var/lib/postgresql/data

  postgresql-fwd-shard2:
    image: postgres:12
    container_name: postgresql-fwd-shard2
    depends_on:
      - postgresql-fwd-master
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    volumes:
      - postgresql-fwd-shard2-volume:/var/lib/postgresql/data

volumes:
  postgresql-fwd-master-volume:
  postgresql-fwd-shard1-volume:
  postgresql-fwd-shard2-volume:
